package com.shirokov.e_commerce_app.config;

public class JwtConstant {
    public static final String SECRET_KEY= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJc3N1ZXIgKGlzcykiOiJJc3N1ZXIiLCJJc3N1ZWQgQXQgKGlhdCkiOiIyMDIzLTEyLTE1VDA1OjQ0OjA2LjcwNVoiLCJFeHBpcmF0aW9uIFRpbWUgKGV4cCkiOiIyMDIzLTEyLTE1VDA2OjQ0OjA2LjcwNVoiLCJTdWJqZWN0IChzdWIpIjoiU3ViamVjdCIsIlVzZXJuYW1lIChhdWQpIjoiSmF2YUd1aWRlcyIsIlJvbGUiOiJBRE1JTiJ9.XrjewWu6VB80CC7uHwH92Iek38Ak6P4iK-wZLEJrzxk";
    public static final String JWT_HEADER= "Authorization";
}
